# Generated by Django 6.0.4 on 2026-05-26 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("iso9001", "ISO 9001"),
                            ("iso22000", "ISO 22000"),
                            ("iso14001", "ISO 14001"),
                            ("iso45001", "ISO 45001"),
                        ],
                        max_length=20,
                    ),
                ),
                ("question", models.TextField()),
                ("requirement", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["standard", "order"],
            },
        ),
        migrations.CreateModel(
            name="AuditSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("internal", "Ichki audit"),
                            ("external", "Tashqi audit"),
                            ("certification", "Sertifikatsiya auditi"),
                            ("surveillance", "Nazorat auditi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("standard", models.CharField(max_length=50)),
                ("planned_date", models.DateField()),
                ("auditor_name", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Rejalashtirilgan"),
                            ("in_progress", "Jarayonda"),
                            ("completed", "Bajarildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["planned_date"],
            },
        ),
        migrations.CreateModel(
            name="NonConformity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("minor", "Kichik"),
                            ("major", "Katta"),
                            ("critical", "Kritik"),
                        ],
                        max_length=20,
                    ),
                ),
                ("assigned_to", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ochiq"),
                            ("in_progress", "Jarayonda"),
                            ("closed", "Yopilgan"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("root_cause", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nonconformities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QMSDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("policy", "Siyosat"),
                            ("procedure", "Protsedura"),
                            ("instruction", "Ko'rsatma"),
                            ("record", "Yozuv"),
                            ("certificate", "Sertifikat"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to="qms_documents/")),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qms_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Mos"),
                            ("partial", "Qisman"),
                            ("non_compliant", "Mos emas"),
                            ("not_checked", "Tekshirilmagan"),
                        ],
                        default="not_checked",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="qms.checklistitem",
                    ),
                ),
            ],
            options={
                "unique_together": {("company", "item")},
            },
        ),
    ]
