# Generated by Django 6.0.4 on 2026-05-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistitem",
            name="clause",
            field=models.CharField(
                blank=True,
                help_text="ISO clause number, e.g. 4.1, 6.2.2",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="checklistresponse",
            name="evidence_text",
            field=models.TextField(
                blank=True, help_text="Evidence: document name, link, or description"
            ),
        ),
    ]
