# Generated by Django 6.0.4 on 2026-05-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0003_qmsdocumentversion"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonconformity",
            name="ai_suggestion",
            field=models.TextField(
                blank=True, help_text="AI taklif qilgan tub sabab va tuzatuvchi chora"
            ),
        ),
        migrations.AddField(
            model_name="nonconformity",
            name="code",
            field=models.CharField(
                blank=True,
                help_text="Izlanadigan raqam, masalan NC-2026-001",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="qmsdocument",
            name="expiry_notified",
            field=models.BooleanField(
                default=False, help_text="Muddat eslatmasi yuborilganmi"
            ),
        ),
    ]
