# Generated by Django 6.0.4 on 2026-06-04 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0004_nonconformity_ai_suggestion_nonconformity_code_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="nonconformity",
            name="is_effective_verified",
            field=models.BooleanField(
                default=False, help_text="Tuzatuvchi chora samarali bo'lganmi?"
            ),
        ),
        migrations.AddField(
            model_name="nonconformity",
            name="verification_note",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="nonconformity",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="RiskItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("iso9001", "ISO 9001"),
                            ("iso14001", "ISO 14001"),
                            ("iso45001", "ISO 45001"),
                            ("iso22000", "ISO 22000"),
                        ],
                        default="iso9001",
                        max_length=20,
                    ),
                ),
                (
                    "process_area",
                    models.CharField(
                        help_text="Jarayon yoki bo'lim nomi", max_length=200
                    ),
                ),
                ("description", models.TextField(help_text="Risk tavsifi")),
                (
                    "likelihood",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                (
                    "impact",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
                (
                    "mitigation",
                    models.TextField(
                        blank=True, help_text="Riskni kamaytirish choralari"
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True, help_text="Masul shaxs", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Ochiq"),
                            ("mitigated", "Kamaytarilgan"),
                            ("accepted", "Qabul qilingan"),
                            ("closed", "Yopilgan"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=200)),
                ("position", models.CharField(blank=True, max_length=200)),
                ("training_name", models.CharField(max_length=300)),
                (
                    "standard_clause",
                    models.CharField(
                        blank=True, help_text="Masalan: ISO 9001 7.2", max_length=100
                    ),
                ),
                ("date_completed", models.DateField()),
                ("trainer", models.CharField(blank=True, max_length=200)),
                ("certificate_number", models.CharField(blank=True, max_length=100)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date_completed"],
            },
        ),
    ]
