# Generated by Django 6.0.4 on 2026-06-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qms", "0005_risk_training_nc_effectiveness"),
    ]

    operations = [
        migrations.AddField(
            model_name="qmsdocument",
            name="ai_content",
            field=models.TextField(
                blank=True, help_text="AI tomonidan yaratilgan hujjat matni (markdown)"
            ),
        ),
    ]
