# Generated by Django 6.0.4 on 2026-05-26 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experts", "0004_project_sla_deadline_project_sla_hours_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("quality_policy", "Sifat siyosati"),
                            ("procedure", "Protsedura"),
                            ("instruction", "Ish ko'rsatmasi"),
                            ("audit_report", "Audit hisoboti"),
                            ("corrective_action", "Tuzatuvchi chora"),
                            ("management_review", "Menejment sharhi"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("iso9001", "ISO 9001"),
                            ("iso22000", "ISO 22000"),
                            ("iso14001", "ISO 14001"),
                            ("iso45001", "ISO 45001"),
                        ],
                        max_length=20,
                    ),
                ),
                ("template_content", models.TextField()),
                ("ai_prompt", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["standard", "title"],
            },
        ),
        migrations.CreateModel(
            name="AuditChecklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=300)),
                ("standard", models.CharField(max_length=20)),
                ("audit_date", models.DateField()),
                ("overall_score", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_checklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_checklists",
                        to="experts.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-audit_date"],
            },
        ),
        migrations.CreateModel(
            name="AuditChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clause", models.CharField(max_length=20)),
                ("question", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compliant", "Mos"),
                            ("partial", "Qisman"),
                            ("non_compliant", "Mos emas"),
                            ("not_checked", "Tekshirilmagan"),
                        ],
                        default="not_checked",
                        max_length=20,
                    ),
                ),
                ("evidence", models.TextField(blank=True)),
                ("finding", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
                (
                    "checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="expert_tools.auditchecklist",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ClientCRM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=300)),
                ("contact_person", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("target_standard", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("lead", "Potensial"),
                            ("active", "Faol"),
                            ("completed", "Yakunlangan"),
                            ("paused", "To'xtatilgan"),
                        ],
                        default="lead",
                        max_length=20,
                    ),
                ),
                ("next_followup", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_clients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crm_entries",
                        to="experts.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="CRMNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_notes",
                        to="expert_tools.clientcrm",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qoralama"),
                            ("sent", "Yuborilgan"),
                            ("approved", "Tasdiqlangan"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_docs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="generated_docs",
                        to="experts.project",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="expert_tools.documenttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                (
                    "standard",
                    models.CharField(
                        choices=[
                            ("iso9001", "ISO 9001"),
                            ("iso22000", "ISO 22000"),
                            ("iso14001", "ISO 14001"),
                            ("iso45001", "ISO 45001"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("total_days", models.IntegerField(default=90)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["standard", "title"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplateStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("duration_days", models.IntegerField()),
                ("order", models.IntegerField()),
                ("deliverable", models.CharField(blank=True, max_length=300)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="expert_tools.projecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
