# Generated by Django 6.0.5 on 2026-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="certificates",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="completion_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="project_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="region",
            field=models.CharField(
                blank=True,
                choices=[
                    ("toshkent", "Toshkent"),
                    ("fargona", "Farg'ona"),
                    ("samarqand", "Samarqand"),
                    ("buxoro", "Buxoro"),
                    ("andijon", "Andijon"),
                    ("namangan", "Namangan"),
                    ("qashqadaryo", "Qashqadaryo"),
                    ("surxondaryo", "Surxondaryo"),
                    ("xorazm", "Xorazm"),
                    ("navoiy", "Navoiy"),
                    ("jizzax", "Jizzax"),
                    ("sirdaryo", "Sirdaryo"),
                    ("qoraqalpogiston", "Qoraqalpog'iston"),
                ],
                max_length=50,
            ),
        ),
    ]
