# Generated by Django 6.0.5 on 2026-05-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_expertprofile_certificates_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="verified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
