# Generated by Django 6.0.4 on 2026-05-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_referral_code_customuser_referred_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="cert_expiry",
            field=models.DateField(
                blank=True, help_text="Sertifikat amal qilish muddati", null=True
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="cert_number",
            field=models.CharField(
                blank=True,
                help_text="Sertifikat raqami (masalan: CB-2024-1234)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="expertprofile",
            name="issuing_body",
            field=models.CharField(
                blank=True, help_text="Sertifikat bergan tashkilot", max_length=200
            ),
        ),
    ]
