# Generated by Django 6.0.5 on 2026-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_expertprofile_credential_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="expertprofile",
            name="standard_tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
