# Generated by Django 6.0.4 on 2026-06-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_standard_tags_work_deadline_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="preferred_language",
            field=models.CharField(
                choices=[("uz", "O'zbek"), ("ru", "Русский"), ("en", "English")],
                default="uz",
                max_length=5,
            ),
        ),
    ]
