# Generated by Django 6.0.4 on 2026-06-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_preferred_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verify_token",
            field=models.CharField(blank=True, db_index=True, max_length=72),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_email_verified",
            field=models.BooleanField(default=True),
        ),
    ]
