# Generated by Django 6.0.4 on 2026-06-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_add_comment_like_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="language",
            field=models.CharField(
                choices=[("uz", "O'zbek"), ("ru", "Русский"), ("en", "English")],
                default="uz",
                max_length=5,
            ),
        ),
    ]
