# Generated by Django 6.0.4 on 2026-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_add_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="group_key",
            field=models.SlugField(
                blank=True,
                help_text="Bir xil maqolaning turli tillari uchun umumiy kalit",
                max_length=200,
            ),
        ),
    ]
