# Generated by Django 6.0.5 on 2026-05-23 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=500)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("local", "Mahalliy (UzDST/GOST)"),
                            ("international", "Xalqaro (ISO/CE/EN)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=200)),
                ("version", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="GapAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_info", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("in_progress", "Jarayonda"),
                            ("completed", "Bajarildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("ai_result", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entrepreneur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "local_standard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="local_analyses",
                        to="analysis.standard",
                    ),
                ),
                (
                    "target_standard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_analyses",
                        to="analysis.standard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("critical", "Kritik"),
                            ("high", "Yuqori"),
                            ("medium", "O'rta"),
                            ("low", "Past"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
                ("estimated_days", models.IntegerField(default=0)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gaps",
                        to="analysis.gapanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_days", models.IntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap",
                        to="analysis.gapanalysis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("duration_days", models.IntegerField(default=0)),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="analysis.roadmap",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
