# Generated by Django 6.0.5 on 2026-05-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_industry_gapanalysis_industry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500)),
                ("help_text", models.CharField(blank=True, max_length=500)),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Ha / Yo'q"),
                            ("yes_partial_no", "Ha / Qisman / Yo'q"),
                            ("scale", "Baho (1-5)"),
                        ],
                        default="yes_partial_no",
                        max_length=20,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="analysis.standard",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[("yes", "Ha"), ("partial", "Qisman"), ("no", "Yo'q")],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="analysis.gapanalysis",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analysis.question",
                    ),
                ),
            ],
        ),
    ]
