# Generated by Django 6.0.5 on 2026-06-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_disclaimeracceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="roadmapstep",
            name="deliverables",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Tayyorlanadigan hujjat/natijalar ro'yxati",
            ),
        ),
    ]
