# Generated by Django 6.0.4 on 2026-06-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_roadmapstep_deliverables"),
    ]

    operations = [
        migrations.AddField(
            model_name="gapanalysis",
            name="language",
            field=models.CharField(default="uz", max_length=5),
        ),
    ]
