# Generated by Django 6.0.4 on 2026-06-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_add_language_to_gapanalysis"),
    ]

    operations = [
        migrations.CreateModel(
            name="StandardRoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("deliverables", models.JSONField(default=list)),
                ("duration_days", models.IntegerField(default=14)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "standard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap_template_steps",
                        to="analysis.standard",
                    ),
                ),
            ],
            options={
                "ordering": ["standard", "order"],
            },
        ),
    ]
