# Generated by Django 6.0.4 on 2026-06-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0007_standard_roadmap_step"),
    ]

    operations = [
        migrations.AddField(
            model_name="gapitem",
            name="clause",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
