# Generated by Django 6.0.4 on 2026-06-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0008_gap_item_clause"),
    ]

    operations = [
        migrations.AddField(
            model_name="industry",
            name="description_en",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="industry",
            name="description_ru",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="industry",
            name="name_en",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="industry",
            name="name_ru",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="question",
            name="help_text_en",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="question",
            name="help_text_ru",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="question",
            name="text_en",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="question",
            name="text_ru",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="standard",
            name="description_en",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="description_ru",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="standard",
            name="name_en",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="standard",
            name="name_ru",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
