# Generated by Django 6.0.5 on 2026-05-23 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0003_question_questionanswer"),
        ("experts", "0002_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="budget",
            new_name="expert_price",
        ),
        migrations.AddField(
            model_name="project",
            name="entrepreneur_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="expert_days",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="project",
            name="expert_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectupdate",
            name="update_type",
            field=models.CharField(
                choices=[
                    ("message", "Xabar"),
                    ("progress", "Progress"),
                    ("document", "Hujjat"),
                    ("completed", "Yakunlandi"),
                ],
                default="message",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="analysis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="analysis.gapanalysis",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Taklif yuborildi"),
                    ("negotiating", "Narx kelishilmoqda"),
                    ("accepted", "Qabul qilindi"),
                    ("in_progress", "Jarayonda"),
                    ("review", "Tekshiruvda"),
                    ("completed", "Bajarildi"),
                    ("cancelled", "Bekor qilindi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("card_number", models.CharField(blank=True, max_length=20)),
                ("card_holder", models.CharField(blank=True, max_length=100)),
                ("card_expiry", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("income", "Kirim"),
                            ("withdrawal", "Chiqim"),
                            ("refund", "Qaytarish"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="experts.project",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="experts.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
