# Generated by Django 6.0.4 on 2026-05-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0003_rename_budget_project_expert_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="sla_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="sla_hours",
            field=models.IntegerField(default=72),
        ),
        migrations.AddField(
            model_name="project",
            name="sla_status",
            field=models.CharField(
                choices=[
                    ("on_time", "Vaqtida"),
                    ("warning", "Ogohlantirish"),
                    ("breached", "Muddat o'tdi"),
                ],
                default="on_time",
                max_length=20,
            ),
        ),
    ]
