# Generated by Django 6.0.5 on 2026-06-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0005_add_withdrawal_request_dispute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="card_number",
            field=models.CharField(max_length=500),
        ),
    ]
