# Generated by Django 6.0.5 on 2026-06-02 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0006_withdrawal_card_encrypted"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="counter_message",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="counter_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="counter_status",
            field=models.CharField(
                choices=[
                    ("none", "Yo'q"),
                    ("pending", "Kutilmoqda"),
                    ("accepted", "Qabul qilindi"),
                    ("rejected", "Rad etildi"),
                ],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="work_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
