# Generated by Django 6.0.4 on 2026-06-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0007_standard_tags_work_deadline_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
