# Generated by Django 6.0.4 on 2026-06-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0008_notification_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="review_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
