# Generated by Django 6.0.4 on 2026-06-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0009_project_review_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectupdate",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="chat_files/"),
        ),
        migrations.AddField(
            model_name="projectupdate",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="projectupdate",
            name="message",
            field=models.TextField(blank=True),
        ),
    ]
