# Generated by Django 6.0.4 on 2026-06-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experts", "0010_add_file_to_projectupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="counter_rounds",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
